### PR TITLE
Logo-Creation pull request

### PR DESCRIPTION
**Pull request by NotSoEpicGuy**
yes

### CODE REVIEW

**Review by Smilin-Dominator — CHANGES_REQUESTED** [review]
Please move the image to src/main/resources/logos/

**Review by Smilin-Dominator — APPROVED** [review]
Cool, now just upgrade / improve and merge when you're done

**Comment by Smilin-Dominator** [comment]
Hey @NotSoEpicGuy , small tip. Don't make the first line (subject) of the commit too long; Just make it condensed and put all the information you need after the first line.

**Comment by NotSoEpicGuy** [comment]
Sure thing.

**Comment by Smilin-Dominator** [comment]
Follow this; https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/amp/

And take a look at my commits to get an idea

**Comment by Smilin-Dominator** [comment]
Manish, check the file called resources that I merged to main, after you
finish the logo so that you can test how it fits and all.

**Comment by Smilin-Dominator** [comment]
I'll merge the latest changes of main to this, hold on

**Review by Smilin-Dominator — CHANGES_REQUESTED** [review]
Tasks
- [ ] Upgrade the logo to a better font
- [ ] Make the logo more lively, eye catching
- [ ] Experiment with the new class I made to determine it's size as well.

**Comment by Smilin-Dominator** [comment]
The Colour Palette;

**Comment by Smilin-Dominator** [comment]
On second thoughts, do you want to change the colours or the font? They don't really fit together.

**Comment by Smilin-Dominator** [comment]
Also please complete this by today, otherwise alot of time will be wasted waiting for this.

**Comment by NotSoEpicGuy** [comment]
> On second thoughts, do you want to change the colors or the font? They don't really fit together.

The colors are a bit "meh" at best (no offense) when being placed on the text, but I personally like the font.
Anyways, we'll go with anything, you can decide what to change, no problem for me.

**Comment by NotSoEpicGuy** [comment]
> Manish, check the file called resources that I merged to main, after you finish the logo so that you can test how it fits and all.

There's a file called resources? Where is it located?

**Comment by Smilin-Dominator** [comment]
> > On second thoughts, do you want to change the colors or the font? They don't really fit together.
> 
> 
> 
> The colors are a bit "meh" at best (no offense) when being placed on the text, but I personally like the font.
> 
> Anyways, we'll go with anything, you can decide what to change, no problem for me.

You could've told me before you designed it, now time = wasted. Design a new one.

**Comment by Smilin-Dominator** [comment]
> > Manish, check the file called resources that I merged to main, after you finish the logo so that you can test how it fits and all.
> 
> 
> 
> There's a file called resources? Where is it located? Respond soon please, I can't find this on my own

For God's Sake, did you pull?

**Comment by Smilin-Dominator** [comment]
Read the changelog

**Comment by Smilin-Dominator** [comment]
Create a colour scheme and send the logo drafts here. I expect this to be done by tomorrow night.

**Comment by NotSoEpicGuy** [comment]
hadn't checked this pr, sorry bout that, got 2 shield (not badge) designs, does the color palette need changing too? let me know on what you think and tell me if I should look for something better/more advanced

image
image

**Comment by NotSoEpicGuy** [comment]
> 2nd is better, I'd suggest creating a new scheme

Scheme as in color scheme?

**Comment by Smilin-Dominator** [comment]
> > 2nd is better, I'd suggest creating a new scheme
> 
> 
> 
> Scheme as in color scheme?

Pyramid Scheme😈📈
Yeah, the colour scheme

**Comment by NotSoEpicGuy** [comment]
dark, light, different shades of a singular color?

**Comment by Smilin-Dominator** [comment]
You decide, don't rely on me for everything. You're the design manager after all😎

**Pull request merged**
